export const ABILITY_LIST = [
  // English
  "PRODUCTION(?: [1-9]| X)?",
  "ANTI-FIGHTER BARRAGE(?: [1-9] \(x[1-9]\))?",
  "BOMBARDMENT(?: [1-9] \(x[1-9]\))?",
  "SPACE CANNON(?: [1-9](?: \(x[1-9]\))?)?",
  "SUSTAIN DAMAGE",
  "PLANETARY SHIELD",
  "MOVE",
  "COMBAT",
  "CAPACITY",
  "COST",
  "MITOSIS",
  "AWAKEN",
  "COALESCENCE",
  "STAR FORGE",
  "ORBITAL DROP",
  "PILLAGE",
  "TELEPATHIC",
  "TECHNOLOGICAL SINGULARITY",
  "FRAGILE",
  "INDOCTRINATION",
  "SCHEMING",
  "STALL TACTICS",
  "FABRICATION",
  "BLACK MARKET FORGERY",
  "DARK ENERGY TAP",
  "X-89 BACTERIAL WEAPON",
  "RALLY TO THE CAUSE",
  "RECYCLED MATERIALS",
  "AUTONETIC MEMORY",
  "SYNERGY",
  // German
  "PRODUKTION(?: [1-9]| X)?",
  "JÄGERABWEHR(?: [1-9] \(x[1-9]\))?",
  "BOMBARDEMENT(?: [1-9] \(x[1-9]\))?",
  "WELTRAUMKANONE(?: [1-9](?: \(x[1-9]\))?)?",
  "SCHADENSRESISTENZ",
  "PLANETARER SCHILD",
  "BEWEGUNG",
  "KAMPF",
  "KAPAZITÄT",
  "KOSTEN",
  "ZELLTEILUNG",
  "ERWECKEN",
  "VERSCHMELZEN",
  "STERNENSCHMIEDE",
  "ORBITALE LANDUNG",
  "PLÜNDERN",
  "TELEPATHIE",
  "TECHNOLOGISCHE SINGULARITÄT",
  "ZERBRECHLICH",
  "MISSIONIEREN",
  "INTRIGANT",
  "VERZÖGERUNGSTAKTIK",
  "VERARBEITUNG",
  "SCHWARZMARKT-FÄLSCHUNG",
  "NULLPUNKTENERGIE-REAKTOR",
  "BAKTERIELLER KAMPFSTOFF X-89",
  // French
  "PRODUCTION(?: [1-9]| X)?",
  "BARRAGE ANTI-CHASSEUR(?: [1-9] \(x[1-9]\))?",
  "BOMBARDEMENT(?: [1-9] \(x[1-9]\))?",
  "CANON SPATIAL(?: [1-9](?: \(x[1-9]\))?)?",
  "DEGATS ENCAISSES",
  "BOUCLIER PLANÉTAIRE",
  "DEPLACEMENT",
  "COMBAT",
  "CAPACITE",
  "COUT",
  "MITOSE",
  "RÉVEIL",
  "COALESCENCE",
  "FOREGE STELLAIRE",
  "LARGAGE ORBITAL",
  "PILLAGE",
  "TÉLÉPATHIE",
  "SINGULARITÉ TECHNOLOGIQUE",
  "FRAGILE",
  "ENDOCTRINEMENT",
  "MACHINATION",
  "GAIN DE TEMPS",
  "FABRICATION",
  "CONTRE FAÇON DU MARCHÉ NOIR",
  // Russian
  "ПРОИЗВОДСТВО(?: [1-9]| X)?",
  "ЗАГРАДИТЕЛЬНЫЙ ОГОНЬ(?: [1-9] \(x[1-9]\))?",
  "БОМБАРДИРОВКА(?: [1-9] \(x[1-9]\))?",
  "КОСМИЧЕСКАЯ ПУШКА(?: [1-9](?: \(x[1-9]\))?)?",
  "ПОГЛОЩЕНИЕ УРОНА",
  "ПЛАНЕТАРНЫЙ ЩИТ",
  "ПОЛЕТ",
  "БОЙ",
  "МЕСТО",
  "ЦЕНА",
  "МИТОЗ",
  "ПРОБУЖДЕНИЕ",
  "СРАСТАНИЕ",
  "ЗВЁЗДНАЯ КУЗНЯ",
  "ОРБИТАЛЬНЫЙ ДЕСАНТ",
  "МАРОДЁРСТВО",
  "ТЕЛЕПАТИЯ",
  "ТЕХНОЛОГИЧЕСКАЯ СИНГУЛЯРНОСТЬ",
  "ХРУПКОСТЬ",
  "ПРОПАГАНДА",
  "ИНТРИГИ",
  "ОТВЛЕКАЮЩИЙ МАНЁВР",
  "ПОДДЕЛКА",
  "ПОДДЕЛКА С ЧЕРНОГО РЫНКА",
  "ИСТОЧНИК ТЕМНОЙ ЭНЕРГИИ",
  "БАКТЕРИОЛОГИЧЕСКОЕ ОРУЖИЕ X-89",
  // Polish
  "OSTRZAŁ PRZECIWMYŚLIWSKI(?: [1-9] \(x[1-9]\))?",
  "PRODUKCJA(?: [1-9]| X)?",
  "BOMBARDOWANIE(?: [1-9] \(x[1-9]\))?",
  "DZIAŁO KOSMICZNE(?: [1-9](?: \(x[1-9]\))?)?",
  "WYTRZYMAŁOŚĆ",
  "TARCZA PLANETARNA",
  "RUCH",
  "WALKA",
  "ŁADOWNOŚĆ",
  "KOSZT",
  "MITOZA",
  "PRZEBUDZENIE",
  "WSPÓŁISTNIENIE",
  "GWIEZDNA KUŹNIA",
  "DESANT ORBITALNY",
  "GRABIEŻ",
  "TELEPATIA",
  "TECHNOLOGICZNA OSOBLIWOŚĆ",
  "DELIKATNI",
  "INDOKTRYNACJA",
  "INTRYGANCI",
  "GRA NA ZWŁOKĘ",
  "PODRÓBKA",
  "CZARNORYNKOWA PODRÓBKA",
  "KONWENTER CIEMNEJ ENERGII",
  "BROŃ BAKTERIOLOGICZNA X-89",
  "SYNERGIA",
] as const;
