const PLANETS = [
  {
    name: "Abaddon",
    resources: 1,
    influence: 0,
    type: "Cultural",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Abyz",
    resources: 3,
    influence: 0,
    type: "Hazardous",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Accoen",
    resources: 2,
    influence: 3,
    type: "Industrial",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Alio Prima",
    resources: 1,
    influence: 1,
    type: "Cultural",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Ang",
    resources: 2,
    influence: 0,
    type: "Industrial",
    home: false,
    attributes: ["red-skip"],
    attachments: [],
    isReady: true,
  },
  {
    name: "Archon Vail",
    resources: 1,
    influence: 3,
    type: "Hazardous",
    home: false,
    attributes: ["blue-skip"],
    attachments: [],
    isReady: true,
  },
  {
    name: "Arinam",
    resources: 1,
    influence: 2,
    type: "Industrial",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Arnor",
    resources: 1,
    influence: 2,
    type: "Industrial",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Ashtroth",
    resources: 2,
    influence: 0,
    type: "Hazardous",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Atlas",
    resources: 3,
    influence: 1,
    type: "Hazardous",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Ba'kal",
    resources: 3,
    influence: 2,
    type: "Industrial",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Bereg",
    resources: 3,
    influence: 1,
    type: "Hazardous",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Cealdri",
    resources: 0,
    influence: 2,
    type: "Cultural",
    home: false,
    attributes: ["yellow-skip"],
    attachments: [],
    isReady: true,
  },
  {
    name: "Centauri",
    resources: 1,
    influence: 3,
    type: "Cultural",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Coorneeq",
    resources: 1,
    influence: 2,
    type: "Cultural",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Cormund",
    resources: 2,
    influence: 0,
    type: "Hazardous",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Dal Bootha",
    resources: 0,
    influence: 2,
    type: "Cultural",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Everra",
    resources: 3,
    influence: 1,
    type: "Cultural",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Fria",
    resources: 2,
    influence: 0,
    type: "Hazardous",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Gral",
    resources: 1,
    influence: 1,
    type: "Industrial",
    home: false,
    attributes: ["blue-skip"],
    attachments: [],
    isReady: true,
  },
  {
    name: "Hope's End",
    resources: 3,
    influence: 0,
    type: "Hazardous",
    home: false,
    attributes: ["legendary"],
    attachments: [],
    isReady: true,
  },
  {
    name: "Jeol Ir",
    resources: 2,
    influence: 3,
    type: "Industrial",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Krag",
    resources: 2,
    influence: 1,
    type: "Hazardous",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Lazar",
    resources: 1,
    influence: 0,
    type: "Cultural",
    home: false,
    attributes: ["yellow-skip"],
    attachments: [],
    isReady: true,
  },
  {
    name: "Lisis",
    resources: 2,
    influence: 2,
    type: "Industrial",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Lirta IV",
    resources: 2,
    influence: 3,
    type: "Hazardous",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Lodor",
    resources: 3,
    influence: 1,
    type: "Cultural",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Loki",
    resources: 1,
    influence: 2,
    type: "Cultural",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Lor",
    resources: 2,
    influence: 1,
    type: "Industrial",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Mallice",
    resources: 0,
    influence: 3,
    type: "Cultural",
    home: false,
    attributes: ["legendary"],
    attachments: [],
    isReady: true,
  },
  {
    name: "Mecatol Rex",
    resources: 1,
    influence: 6,
    type: "none",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Meer",
    resources: 0,
    influence: 4,
    type: "Hazardous",
    home: false,
    attributes: ["red-skip"],
    attachments: [],
    isReady: true,
  },
  {
    name: "Mehar Xull",
    resources: 1,
    influence: 3,
    type: "Hazardous",
    home: false,
    attributes: ["red-skip"],
    attachments: [],
    isReady: true,
  },
  {
    name: "Mellon",
    resources: 0,
    influence: 2,
    type: "Cultural",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Mirage",
    resources: 1,
    influence: 2,
    type: "Cultural",
    home: false,
    attributes: ["legendary"],
    attachments: [],
    isReady: true,
  },
  {
    name: "New Albion",
    resources: 1,
    influence: 1,
    type: "Industrial",
    home: false,
    attributes: ["green-skip"],
    attachments: [],
    isReady: true,
  },
  {
    name: "Perimeter",
    resources: 2,
    influence: 1,
    type: "Industrial",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Primor",
    resources: 2,
    influence: 1,
    type: "Cultural",
    home: false,
    attributes: ["legendary"],
    attachments: [],
    isReady: true,
  },
  {
    name: "Quann",
    resources: 2,
    influence: 1,
    type: "Cultural",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Qucen'n",
    resources: 1,
    influence: 2,
    type: "Industrial",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Rarron",
    resources: 0,
    influence: 3,
    type: "Cultural",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Resculon",
    resources: 2,
    influence: 0,
    type: "Cultural",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Rigel I",
    resources: 0,
    influence: 1,
    type: "Hazardous",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Rigel II",
    resources: 1,
    influence: 2,
    type: "Industrial",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Rigel III",
    resources: 1,
    influence: 1,
    type: "Industrial",
    home: false,
    attributes: ["green-skip"],
    attachments: [],
    isReady: true,
  },
  {
    name: "Saudor",
    resources: 2,
    influence: 2,
    type: "Industrial",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Sakulag",
    resources: 2,
    influence: 1,
    type: "Hazardous",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Sem-Lore",
    resources: 3,
    influence: 2,
    type: "Cultural",
    home: false,
    attributes: ["yellow-skip"],
    attachments: [],
    isReady: true,
  },
  {
    name: "Siig",
    resources: 0,
    influence: 2,
    type: "Hazardous",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Starpoint",
    resources: 3,
    influence: 1,
    type: "Hazardous",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Tar'Mann",
    resources: 1,
    influence: 1,
    type: "Industrial",
    home: false,
    attributes: ["green-skip"],
    attachments: [],
    isReady: true,
  },
  {
    name: "Tequ'ran",
    resources: 2,
    influence: 0,
    type: "Hazardous",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Thibah",
    resources: 1,
    influence: 1,
    type: "Industrial",
    home: false,
    attributes: ["blue-skip"],
    attachments: [],
    isReady: true,
  },
  {
    name: "Torkan",
    resources: 0,
    influence: 3,
    type: "Cultural",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Vefut II",
    resources: 2,
    influence: 2,
    type: "Hazardous",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Vega Major",
    resources: 2,
    influence: 1,
    type: "Cultural",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Vega Minor",
    resources: 1,
    influence: 2,
    type: "Cultural",
    home: false,
    attributes: ["blue-skip"],
    attachments: [],
    isReady: true,
  },
  {
    name: "Velnor",
    resources: 2,
    influence: 1,
    type: "Industrial",
    home: false,
    attributes: ["red-skip"],
    attachments: [],
    isReady: true,
  },
  {
    name: "Vorhal",
    resources: 0,
    influence: 2,
    type: "Cultural",
    home: false,
    attributes: ["green-skip"],
    attachments: [],
    isReady: true,
  },
  {
    name: "Wellon",
    resources: 1,
    influence: 2,
    type: "Industrial",
    home: false,
    attributes: ["yellow-skip"],
    attachments: [],
    isReady: true,
  },
  {
    name: "Xanhact",
    resources: 0,
    influence: 1,
    type: "Hazardous",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Xxehan",
    resources: 1,
    influence: 1,
    type: "Cultural",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    name: "Zohbat",
    resources: 3,
    influence: 1,
    type: "Hazardous",
    home: false,
    attributes: [],
    attachments: [],
    isReady: true,
  },
];
const HOME_PLANETS = [
  {
    faction: "Arborec",
    name: "Nestphar",
    resources: 3,
    influence: 2,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Barony of Letnev",
    name: "Arc Prime",
    resources: 4,
    influence: 0,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Barony of Letnev",
    name: "Wren Terra",
    resources: 2,
    influence: 1,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Clan of Saar",
    name: "Lisis II",
    resources: 1,
    influence: 0,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Clan of Saar",
    name: "Ragh",
    resources: 2,
    influence: 1,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Embers of Muaat",
    name: "Muaat",
    resources: 4,
    influence: 1,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Emirates of Hacan",
    name: "Hercant",
    resources: 1,
    influence: 1,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Emirates of Hacan",
    name: "Arretze",
    resources: 2,
    influence: 0,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Emirates of Hacan",
    name: "Kamdorn",
    resources: 0,
    influence: 1,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Federation of Sol",
    name: "Jord",
    resources: 4,
    influence: 2,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Ghosts of Creuss",
    name: "Creuss",
    resources: 4,
    influence: 2,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "L1Z1X Mindnet",
    name: "[0.0.0]",
    resources: 5,
    influence: 0,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Mentak Coalition",
    name: "Moll Primus",
    resources: 4,
    influence: 1,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Naalu Collective",
    name: "Druaa",
    resources: 3,
    influence: 1,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Naalu Collective",
    name: "Maaluuk",
    resources: 0,
    influence: 2,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Nekro Virus",
    name: "Mordai II",
    resources: 4,
    influence: 0,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Sardakk N'orr",
    name: "Tren'Lak",
    resources: 1,
    influence: 0,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Sardakk N'orr",
    name: "Quinarra",
    resources: 3,
    influence: 1,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Universities of Jol-Nar",
    name: "Jol",
    resources: 1,
    influence: 2,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Universities of Jol-Nar",
    name: "Nar",
    resources: 2,
    influence: 3,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Winnu",
    name: "Winnu",
    resources: 3,
    influence: 4,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Xxcha Kingdom",
    name: "Archon Ren",
    resources: 2,
    influence: 3,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Xxcha Kingdom",
    name: "Archon Tau",
    resources: 1,
    influence: 1,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Yin Brotherhood",
    name: "Darien",
    resources: 4,
    influence: 4,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Yssaril Tribes",
    name: "Retillion",
    resources: 2,
    influence: 3,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Yssaril Tribes",
    name: "Shalloq",
    resources: 1,
    influence: 2,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Argent Flight",
    name: "Valk",
    resources: 2,
    influence: 0,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Argent Flight",
    name: "Avar",
    resources: 1,
    influence: 1,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Argent Flight",
    name: "Ylir",
    resources: 0,
    influence: 2,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Empyrean",
    name: "The Dark",
    resources: 3,
    influence: 4,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Mahact Gene-Sorcerers",
    name: "Ixth",
    resources: 3,
    influence: 5,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Naaz-Rokha Alliance",
    name: "Naazir",
    resources: 2,
    influence: 1,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Naaz-Rokha Alliance",
    name: "Rokha",
    resources: 1,
    influence: 2,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Nomad",
    name: "Arcturus",
    resources: 4,
    influence: 4,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Titans of Ul",
    name: "Elysium",
    resources: 4,
    influence: 1,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
  {
    faction: "Vuil'Raith Cabal",
    name: "Acheron",
    resources: 4,
    influence: 0,
    type: "none",
    home: true,
    attributes: [],
    attachments: [],
    isReady: true,
  },
]
export default function handler(req, res) {
  res.status(200).json([...PLANETS, ...HOME_PLANETS]);
}