type LeaderState = "locked" | "readied" | "purged" | "exhausted";

type LeaderId =
  | "2RAM"
  | "Acamar"
  | "Adjudicator Ba'al"
  | "Airo Shir Aur"
  | "Ahk-Syl Siven"
  | "Artuno the Betrayer"
  | "Berekar Berekon"
  | "Brother Milor"
  | "Brother Omar"
  | "Captain Mendosa"
  | "Carth of Golden Sands"
  | "Claire Gibson"
  | "Conservator Procyon"
  | "Dannel of the Tenth"
  | "Darktalon Treilla"
  | "Dart and Tai"
  | "Dirzuga Rophal"
  | "Doctor Sucaban"
  | "Elder Qanoj"
  | "Emissary Taivra"
  | "Evelyn Delouis"
  | "Field Marshal Mercer"
  | "Garv and Gunn"
  | "Ggrocuto Rinn"
  | "G'hom Sek'kus"
  | "Gila the Silvertongue"
  | "Gurno Aggero"
  | "Harka Leeds"
  | "Harrugh Gefhara"
  | "Hesh and Prit"
  | "I48S"
  | "Il Na Viroset"
  | "Ipswitch Loose Cannon"
  | "It Feeds on Carrion"
  | "Jace X 4th Air Legion"
  | "Jae Mir Kan"
  | "Kuuasi Aun Jalatai"
  | "Kyver Blade and Key"
  | "Letani Miasmiala"
  | "Letani Ospha"
  | "M'aban"
  | "Magmus"
  | "Mathis Mathinus"
  | "Mirik Aun Sissiri"
  | "Navarch Feng"
  | "Nekro Acidos"
  | "Nekro Malleon"
  | "Odlynn Myrr"
  | "Rear Admiral Farran"
  | "Rickar Rickani"
  | "Riftwalker Meian"
  | "Rin The Master's Legacy"
  | "Rowl Sarrig"
  | "Sai Seravus"
  | "Sh'val Harbinger"
  | "So Ata"
  | "Ssruu"
  | "S'Ula Mentarion"
  | "Suffi An"
  | "Suffi An (Council)"
  | "Ta Zern"
  | "Tellurian"
  | "That Which Molds Flesh"
  | "The Helmsman"
  | "The Oracle"
  | "The Stillness of Stars"
  | "The Thundarian"
  | "T'ro"
  | "Trrakan Aun Zulok"
  | "Trillossa Aun Mirik"
  | "Tungstantus"
  | "Ul the Progenitor"
  | "Umbat"
  | "UNITDSGNFLAYESH"
  | "Viscount Unlenn"
  | "Xander Alexin Victori III"
  | "Xuange"
  | "Xxekir Grom"
  | "Z'eu"
  | DiscordantStars.LeaderId;
